CC :=g++ -std=c++17


all: MainProcess MapProcess ReduceProcess 


MainProcess:
	$(CC) MainProcess.cpp -o MainProcess.out

MapProcess:
	$(CC) MapProcess.cpp -o MapProcess.out

ReduceProcess:
	$(CC) ReduceProcess.cpp -o ReduceProcess.out

rm:
	rm -rf *.out 
